### ISSUE TITLE
Regarding use of regex

### ISSUE THREAD

**Issue by arhankundu99** [snguyenthanh/better_profanity#14]
Instead of generating distorted profane words from the list of profane words, can't we use regex?

**Comment by snguyenthanh** [comment]
Using regex, the runtime will increase exponentially with the length of the input text. [The original `profanity` package actually uses regex to censor the profane words.](https://github.com/ben174/profanity/blob/master/profanity/profanity.py#L65)

Here is a simple benchmark with a 1000-word text:

```
import timeit

from profanity import profanity as pf
from better_profanity import profanity as bpf


pf.load_words(bpf.CENSOR_WORDSET)

def benchmark(func, text: str):
    return func(text)

if __name__ == "__main__":
    test_str = "<a 1000-word text here>"
    regex_runtime = timeit('benchmark(pf.censor, test_str)', globals=globals(), number=1)
    current_runtime = timeit('benchmark(bpf.censor, test_str)', globals=globals(), number=1)

    print(f"Regex: {regex_runtime}")
    print(f"Current: {current_runtime}")
```

which has the following output:
```
# in seconds
Regex: 26.9981138
Current: 0.0000009468
```

**Comment by arhankundu99** [comment]
Thank you so much for the explanation!
