### ISSUE TITLE
How to replace the swear word with the actual word?

### ISSUE THREAD

**Issue by Akshar-code** [snguyenthanh/better_profanity#29]
Hi, 
In this program, the swear words are replaced with asteriks, for example: F@@K will be shown as ****
But i want change a sentence like "F@@k you" into "Fuck you"

How do i do this?

**Comment by BrandonKMLee** [comment]
You might want to read up on how this software works. It generates variations that add to the blocklist or detection list.
Reversing the process might not yield as accurate of a result as compared to purely detecting word variations.

**Comment by snguyenthanh** [comment]
@BrandonKMLee is right. The library doesn't support uncensoring words (and probably won't in a long time).

The closest thing it can do to support your use case is to check whether a word is a variant of a profanity: `profanity.contains_profanity('H4ndjob')`.
