### ISSUE TITLE
Does not work for Python 3.5

### ISSUE THREAD

**Issue by adarsa** [snguyenthanh/better_profanity#6]
Gets error when running on Python 3.5 : better-profanity requires Python '>3.6' but the running Python is 3.5.0

**Comment by snguyenthanh** [comment]
Thank you for the bug report.
This is due to an unresolved fix in `setup.py`. It will be fixed in the next release `0.3.3` in the next few hours.

**Comment by snguyenthanh** [comment]
`0.3.3` has been released and the issue should have been fixed.
Please have a check again.

**Comment by adarsa** [comment]
The change in setup.py should fix it. thanks.
