### ISSUE TITLE
Why "xXx" is profanity?

### ISSUE THREAD

**Issue by puchyla** [snguyenthanh/better_profanity#7]
The result of such constructions is often TRUE: 
`print(profanity.contains_profanity('xxx_x'))`
or `print(profanity.contains_profanity('xXx'))` and so on.
But I don`t understand why? 
Thanks!

**Comment by snguyenthanh** [comment]
The library uses a [wordlist](https://github.com/snguyenthanh/better_profanity/blob/master/better_profanity/profanity_wordlist.txt) to check if the word is a profanity.

When you run any functions in the library, the input string is always lowercased for string comparison with the wordlist. For example, `xXx` will be converted to `xxx`.
As the word `xxx` is inside the [wordlist](https://github.com/snguyenthanh/better_profanity/blob/master/better_profanity/profanity_wordlist.txt#L137), any variant of it is also a profanity, such as `XXX`, `xxx hello` and `xXx`.

To see which word causes the `contains_profanity` to return `True`, you can run `profanity.censor(<your_word>)` and see which word is replaced with `****`.

**Comment by snguyenthanh** [comment]
If your use case requires that `xxx` is not a profanity, what you can do is to load your custom wordlist, as a `List`, into `profanity`:

```
custom_badwords = ['happy', 'jolly', 'merry']
profanity.load_censor_words(custom_badwords)
```

After this, the words not in `custom_badwords` will cause `contains_profanity` to return `False`.

**Comment by snguyenthanh** [comment]
This issue is closed due to inactivity in 7 days.
